{% set version = "0.3.22" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-aws.s3
  version: {{ version|replace("-", "_") }}

source:
  url:
    - https://github.com/cloudyr/cloudyr.github.io/raw/master/drat/src/contrib/aws.s3_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/aws.s3_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/aws.s3/aws.s3_{{ version }}.tar.gz
  sha256: f63a5a1a4a1a8e641510ed71ec313986f435f6d1ee10961d37334657fbbd9e5f

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-aws.signature >=0.3.7
    - r-base64enc
    - r-curl
    - r-digest
    - r-httr
    - r-xml2 >1.0.0
  run:
    - r-base
    - r-aws.signature >=0.3.7
    - r-base64enc
    - r-curl
    - r-digest
    - r-httr
    - r-xml2 >1.0.0

test:
  commands:
    - $R -e "library('aws.s3')"           # [not win]
    - "\"%R%\" -e \"library('aws.s3')\""  # [win]

about:
  home: https://github.com/cloudyr/aws.s3
  license: GPL-2.0-or-later
  summary: A simple client package for the Amazon Web Services ('AWS') Simple Storage Service ('S3') 'REST' 'API' <https://aws.amazon.com/s3/>.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
