appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: niKi1xxJixGOIk+J+/UYCCFqWVCJSuj7p9AQGLq8yIhbDrZMPx7vBR4pG1RO9lg1/HZa/xFE8Gg55AEJ70kS6C55FRMu2ip0SY7kHBqp5J0jOT4BzJm/XhedI13Vmo+QwoInAvK4ATV7rLQeMO+et0H2+N5kljgF25P3mg6YR0mlWwNVPsUDdl1ZCgpuCoWfo2JOKujyT8Tmm3coSfTxKgGIjQo6izf3/WDXpArveYvAdExxrEXcJc4KBpXoIDlld4QYCpKA37jobatBl0WrKP5iSpFRZVjy9CuhnK5a28FVD5ScD/GTpziKhBABB17YOPNnQc32kpz911L4zDCEeIUmNEgHVO5CDds/QwQ2Ts+5Pakg3rJCtBKuxCzbop8VQe9gTMQ/gl/SNvwnksKyiRqidoORM0PZhPmUvuNu6cj8eu3IuM/2xiLKQHtUiwus1TcSsUzZMPb+3xektK8neNTFtuoytjdCx6VkysTr4FuYBiXOmsMm4me9O+NiNcayBxSA3rkWi7PIL3x/9PQfxMUXwDEC20kqSRgs4PxqvVmtpAi8m0a3z1xWfyV9pRhfuqRlKOOxNCXA8JgkB4x55pluzn29A1AJxCPes5iVW1gWTrV/xAnMTTqAyS27ZBja3FHZQ5SqtC4CluClQpfjGSSdnrCODUerqAVnPJQ3Ufg=
