travis:
  secure:
    BINSTAR_TOKEN: HvvRwTv35vVoGEWRbgo5/TxSTnTLjCuLQLpNlJ01PY8p+OyaX7NJhk774K16S0NaNAjiWNKvbp1RBuvuompo+EBGr84TkGQ0v8pPmnUIb2aCU86BzGa+JKSZsifQKgnNEMeV5a4oThJqcjX4CSbDkzWfG0XvP++suVQs+DsGpUjnAToMjehj54xvawdB1Kb/h/hSMefdwjHZElf5lf7LPbilGdJiSMxriyg0KjkS2iWf8hNtt31zvXYJ7AAk/4YxuKnlCNMowU3DkudVph8gFWPTSadRE7MC0esfoEgJo9SSaehI1tkvqqvr7VcKwwSTE0IIKhWb1SQTQ7okSOfUK3KtGlnFVTgrAU569G6GgluN4lFP4H/iDRd/rENL4ttaHrKss941Y1bppHh8+gDzuzqr57SbEdOpe49Zar3p4sV3Xylg8gLmO/zXbJrmXncRSLecFceZjmTGDF6USmwG6Bh4FaEoc/MAbThZLyriCP2zqroU9brR/HLYy7uFOdaIeau8JWbvYbRQUlW41wkqzKOfHwL1vucPRolVbEa8FxJRYOZKF6hpwUH+FxjwJd4GCv46ObBEWpXDyg1SEXM77NZFYREVJB0bZ9f/TDJka//IUaGJu1qyDcRzn1LEb89pYoqkLtBdmWDDCG3WlQp9/0Mh1CGToThCfFnIlK4kXbQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
